# Generated by Django 5.1.4 on 2025-03-23 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busstops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route_boarding_points',
            field=models.ManyToManyField(related_name='bus_route', to='busstops.boardingpoint'),
        ),
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='busstops.buses'),
        ),
        migrations.AddField(
            model_name='section',
            name='bus_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='busstops.busroute'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_boarding_points',
            field=models.ManyToManyField(related_name='section', to='busstops.boardingpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('bus', 'seat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('bus_route', 'position')},
        ),
    ]
