# Generated by Django 5.1.4 on 2025-04-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='seat_count',
            field=models.PositiveIntegerField(choices=[(0, '0-seater'), (32, '32-seater'), (40, '40-seater'), (52, '52-seater'), (64, '64-seater')], default=0),
        ),
    ]
