# Generated by Django 5.1.4 on 2025-04-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluserprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
