# Generated by Django 5.1.4 on 2025-04-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_normaluserprofile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='lane_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='lane_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
